### ISSUE TITLE
Edit box likes to appear at the bottom when set to top

### ISSUE THREAD

**Issue by Jahfry** [ls-/ls_Glass#43] opened 2024-08-13 05:32 UTC
I'm reasonably new to LSG. It *really* ties my custom UI together. Thank you. 

I've got the Edit bar set to appear Top. And it works a fair amount of the time. 

But once I get a whisper from a friend it likes to drop the edit box to the bottom. Which, unfortunately, is partially below the WoW window at that point. 

I'm not sure it is the whispers that cause it. That's just when I notice it most. 

Is there anything I can do to help with the report? I'm not sure it is whispers causing it specifically. 

If I set channel back to guild (/g) *and* reload, the edit bar goes back to the top. But will eventually get dropped down again.

**Comment by ls-** [comment] 2024-08-20 06:21
Hi, from my limited testing, I couldn't reproduce it. What chat mode you use? Classic or IM? It's a setting in Blizz Social config. And are you using an addon like leatrix plus? There's a similar report from another guy recently, but in his case it's just a conflict with leatrix's submodule since two addons were fighting over a single UI element.

**Comment by Jahfry** [comment] 2024-08-26 22:06
Not using Leatrix. Only addon related to chat (aside from LSG) I'm using is Prat. I've been out of game since filing this but I'll keep trying to nail it down :)

**Comment by ls-** [comment] 2024-09-02 12:49
I can't test anything atm. I had another surgery yesterday and I won't be home until Saturday evening, and even then I'll a bit more time to rest. So this will have to wait until I'm feel even a bit better.

**Comment by Jahfry** [comment] 2024-09-03 02:25
I'm pretty sure now that I've had time to play that it was a conflict where Prat was attaching it to the bottom while LSG was attaching to top. 

I've forced both to top. I'll post back if it happens again (or if it doesn't after extended play). 

Hope you feel better soon, I completely sympathize. Similar issues caused me to have delays between replies as well :)

**Comment by ls-** [comment] 2024-09-10 15:32
Haha, that's why I asked about leatrix, when you said prat, I knew that it's a conflict between addons, but I don't remember what's going on in prat, so I didn't say much. I think you could disable the editbox or whatever module in prat.

Anyway, I'll be closing this one.

**Closed by ls-** 2024-09-10 15:32 UTC
